name: Continuous integration

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: master
      NODE_VERSION: 16.x
    steps:
      - name: Checkout to branch ${{ env.DEFAULT_BRANCH }}
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Run npm install
        run: npm ci

      - name: Code style
        run: npm run lint

      - name: UI E2E Tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true